### ISSUE TITLE
cannot reach the website

### ISSUE THREAD

**Issue by fiala-sns** [MirisWisdom/Albumin#4]
I just found this project but I cannot test it. cloudflare stops me from visiting [https://albumin.miris.design/](url) with  "SSL handshake failed Error code 525 ". Here is theirs trobleshooting link [https://support.cloudflare.com/hc/en-us/articles/200278659](url)
Not sure if it's cloudflare problem or any other on my end.

Hope this info helps.

**Comment by MirisWisdom** [comment]
Hey friend, thank you for catching that -- didn't expect this project to be glanced at these days!

I've recently moved server and haven't gotten around to bringing the project back up. Will have it ready within the next hour.

**Comment by MirisWisdom** [comment]
Got around to bringing it back up -- all should be fine now, thanks again!

Feel free to give it a shot and please don't hesitate to let me know if you encounter any further issues.

**Comment by fiala-sns** [comment]
site work, adding videos looks easy enought, thank you! :-)
